import test from'node:test';import assert from'node:assert/strict';import{JSDOM}from'jsdom';import{SourceTextModule}from'node:vm';import{readFile}from'node:fs/promises';import{fileURLToPath,pathToFileURL}from'node:url';import{resolve,dirname}from'node:path';
const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
async function boot(saved){const dom=new JSDOM('<div id="app"></div><dialog id="dialog"></dialog><div id="toast"></div>',{url:'https://example.test/creator-pocket/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.structuredClone=structuredClone;w.scrollTo=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};if(saved)w.localStorage.setItem('creator-pocket-v1',saved);const context=dom.getInternalVMContext(),cache=new Map();async function load(file){if(cache.has(file))return cache.get(file);const mod=new SourceTextModule(await readFile(file,'utf8'),{context,identifier:pathToFileURL(file).href});cache.set(file,mod);await mod.link(async(specifier,ref)=>load(resolve(dirname(fileURLToPath(ref.identifier)),specifier)));return mod;}await(await load(resolve(root,'src/app.js'))).evaluate();const click=(action,extra='')=>{const el=w.document.querySelector(`[data-action="${action}"]${extra}`);assert.ok(el,`missing action ${action}${extra}`);el.click();return el;};return{dom,w,click,saved:()=>JSON.parse(w.localStorage.getItem('creator-pocket-v1'))};}
test('real controller completes a post, rejects invalid budget, and preserves focus after Continue',async()=>{const b=await boot();try{b.click('compose');b.click('choose-edit','[data-id="cinematic"]');assert.ok(b.w.document.querySelector('[data-action=publish]').disabled);b.click('choose-edit','[data-id="captions"]');b.click('publish');assert.equal(b.saved().totalPosts,1);assert.equal(b.saved().phase,'result');assert.ok(b.w.document.querySelector('.post-card'));b.click('continue');assert.equal(b.saved().day,2);assert.equal(b.saved().totalPosts,1);assert.equal(b.w.document.activeElement.dataset.action,'compose');}finally{b.dom.window.close();}});
test('tab switch and upgrade retain a connected focus destination',async()=>{const b=await boot();try{b.click('tab','[data-tab="room"]');assert.equal(b.w.document.activeElement.id,'main-content');b.click('tab','[data-tab="studio"]');b.click('compose');b.click('publish');b.click('continue');b.click('tab','[data-tab="room"]');b.click('upgrade','[data-gear="lamp"]');assert.equal(b.saved().gear.lamp,1);assert.equal(b.w.document.activeElement.id,'main-content');}finally{b.dom.window.close();}});
test('rest confirmation can cancel without consuming a day',async()=>{const b=await boot();try{b.click('rest');b.click('close');assert.equal(b.saved(),null);b.click('rest');b.click('confirm-rest');assert.equal(b.saved().phase,'result');assert.equal(b.saved().energy,100);b.click('continue');assert.equal(b.saved().day,2);}finally{b.dom.window.close();}});
test('seven rest days reach summary and new week',async()=>{const b=await boot();try{for(let i=0;i<7;i++){b.click('rest');b.click('confirm-rest');b.click('continue');}assert.equal(b.saved().phase,'summary');b.click('next-week');assert.equal(b.saved().week,2);assert.equal(b.saved().phase,'planning');assert.equal(b.w.document.activeElement.id,'main-content');}finally{b.dom.window.close();}});
test('media tab is network-cold and canonical queue additions do not grant game rewards',async()=>{const b=await boot();try{b.click('tab','[data-tab="media"]');assert.equal(b.w.document.querySelectorAll('iframe,script[src],img').length,0);const form=b.w.document.querySelector('#url-form');form.elements.url.value='https://youtu.be/abcdefghijk?si=tracking';form.dispatchEvent(new b.w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(b.saved().followers,240);assert.equal(b.saved().coins,120);assert.equal(b.saved().day,1);const q=JSON.parse(b.w.localStorage.getItem('creator-pocket-queue-v1'));assert.equal(q.at(-1),'https://www.youtube.com/watch?v=abcdefghijk');}finally{b.dom.window.close();}});
test('X external frame is sandboxed and removed before showing a modal',async()=>{const b=await boot();try{b.click('tab','[data-tab="media"]');b.click('select-media','[data-index="2"]');b.click('load-media');const frame=b.w.document.querySelector('iframe');assert.ok(frame);assert.equal(frame.getAttribute('sandbox'),'allow-scripts allow-popups allow-popups-to-escape-sandbox');assert.match(frame.src,/creator-pocket\/x-embed\.html/);b.click('privacy');assert.equal(b.w.document.querySelectorAll('iframe').length,0);assert.equal(b.w.document.querySelectorAll('script[src]').length,0);}finally{b.dom.window.close();}});
test('saved result reopens without replaying rewards',async()=>{const first=await boot();let data;try{first.click('compose');first.click('publish');data=first.w.localStorage.getItem('creator-pocket-v1');}finally{first.dom.window.close();}const b=await boot(data);try{b.click('result');b.click('continue');assert.equal(b.saved().totalPosts,1);assert.equal(b.saved().day,2);}finally{b.dom.window.close();}});
