import test from 'node:test';import assert from 'node:assert/strict';
import {escapeHtml,renderApp,renderComposer,renderResult}from'../src/render.js';import{initialState,getIdeas,publish}from'../src/game.js';
const s=initialState(),d={ideaId:getIdeas(s)[0].id,format:'short',hook:'result',body:'steps',edit:'captions',step:'review'};
test('renderer escapes markup from saved text',()=>{assert.equal(escapeHtml('<script>"&'), '&lt;script&gt;&quot;&amp;');});
test('studio exposes fictional labels and primary creation action',()=>{const html=renderApp(s,{tab:'studio',queue:[],mediaIndex:0});assert.match(html,/ゲーム内/);assert.match(html,/data-action="compose"/);assert.match(html,/マイチャンネル/);assert.doesNotMatch(html,/class="room-art"/);});
test('composer review exposes cost and concern without numeric growth prediction',()=>{const html=renderComposer(s,d);assert.match(html,/ゲーム内に投稿/);assert.match(html,/コイン/);assert.doesNotMatch(html,/相性予想|の見込み/);assert.match(html,/制作時間/);assert.match(html,/元気/);assert.match(html,/data-action="publish"/);});
test('real media page has consent notice, source link and no game rewards',()=>{const html=renderApp(s,{tab:'media',queue:['https://www.youtube.com/watch?v=I7v_xuCDwnM'],mediaIndex:0});assert.match(html,/外部サービス/);assert.match(html,/報酬はありません/);assert.match(html,/youtube.com\/watch/);assert.match(html,/YouTubeで再生/);assert.doesNotMatch(html,/data-action="load-media"/);assert.doesNotMatch(html,/<iframe/);assert.doesNotMatch(html,/<img/);});
test('result explains rewards and routes one guarded continue action',()=>{const html=renderResult(publish(s,d));assert.match(html,/公開したよ/);assert.match(html,/data-action="continue"/);assert.match(html,/ゲーム内/);});
test('X load point states transmitted data before optional details',()=>{const html=renderApp(s,{tab:'media',queue:['https://x.com/SpaceX/status/1732824684683784516'],mediaIndex:0});assert.ok(html.indexOf('IPアドレス')<html.indexOf('<details'));});
test('informational controls meet minimum touch target rules',async()=>{const {readFile}=await import('node:fs/promises');const css=await readFile(new URL('../src/styles.css',import.meta.url),'utf8');assert.match(css,/\.info-button[^}]*min-width:44px/);assert.match(css,/\.hero-actions \.quiet[^}]*min-height:44px/);});
test('immersive feed uses one viewport player and keeps navigation outside it',()=>{const html=renderApp(s,{tab:'media',immersive:true,queue:['https://www.youtube.com/watch?v=I7v_xuCDwnM'],mediaIndex:0});assert.match(html,/class="immersive-feed"/);assert.match(html,/data-action="exit-immersive"/);assert.match(html,/data-swipe-area/);assert.match(html,/プレーヤーの外側/);assert.doesNotMatch(html,/class="bottom-nav"/);assert.match(html,/data-action="next-media"/);});
test('immersive gestures have a full-height external rail and a persistent fullscreen explanation',async()=>{const {JSDOM}=await import('jsdom');const dom=new JSDOM(renderApp(s,{tab:'media',immersive:true,queue:['https://www.youtube.com/watch?v=I7v_xuCDwnM'],mediaIndex:0}));try{const doc=dom.window.document,rail=doc.querySelector('.swipe-rail');assert.ok(rail,'large side swipe rail must exist');assert.ok(rail.matches('[data-swipe-area]'));assert.equal(rail.parentElement,doc.querySelector('#embed-mount').parentElement);assert.equal(doc.querySelector('#embed-mount').contains(rail),false);assert.match(rail.textContent,/上にスワイプ/);assert.match(doc.querySelector('.immersive-gesture-help').textContent,/全画面/);assert.match(doc.querySelector('[data-action=next-media]').textContent,/次の動画/);}finally{dom.window.close();}});

test('composer progressively shows one decision, retains selection, and uses single-select semantics',()=>{for(const step of ['idea','format','hook','body','edit']){const html=renderComposer(s,{...d,step});assert.match(html,/role="radiogroup"/);assert.ok((html.match(/role="radio"/g)||[]).length<=3);assert.doesNotMatch(html,/data-action="publish"/);}});
test('channel shows monetization criteria, fictional silver award and no promised payout',()=>{const v={tab:'channel',channelSection:'income',queue:[],mediaIndex:0};const html=renderApp(s,v);assert.match(html,/1,500/);assert.match(html,/100/);assert.match(html,/実在/);const awards=renderApp(s,{...v,channelSection:'awards'});assert.match(awards,/銀の記念盾/);assert.match(awards,/1,000/);});

test('watch view places the video card before optional interests and metadata',()=>{const html=renderApp(s,{tab:'media',queue:['https://www.youtube.com/watch?v=I7v_xuCDwnM'],mediaIndex:0});assert.ok(html.indexOf('class="media-card"')<html.indexOf('class="interest-picker"'));assert.match(html,/<details class="media-preferences"/);assert.match(html,/外部/);assert.doesNotMatch(html,/実際のYouTube \/ Xの公式埋め込み/);});
test('legacy comment counts are labelled as historical counts, never as zero comments',async()=>{const {readFile}=await import('node:fs/promises'),{restoreState}=await import('../src/game.js'),{renderPostDetail}=await import('../src/render.js');const old=restoreState(await readFile(new URL('./fixtures/legacy-save.json',import.meta.url),'utf8')),html=renderPostDetail(old,old.posts[0].id);assert.match(html,/件数だけ/);assert.doesNotMatch(html,/まだコメントはありません/);});
