import{initialState,getIdeas,preview,publish,rest,continueDay,upgrade,startWeek,restoreState}from'./game.js';
import{validateAutoFeed,mergeMediaQueues,restoreHidden,removeQueueEntry}from'./auto-media.js';
import{swipeDirection,nextFeedIndex}from'./feed.js';
import{SEED_MEDIA,parseMediaUrl,restoreQueue,youtubeEmbedUrl}from'./media.js';
import{renderApp,renderComposer,renderResult,renderSummary,renderPrivacy,icon}from'./render.js';
const SAVE='creator-pocket-v1',QUEUE='creator-pocket-queue-v1',HIDDEN='creator-pocket-hidden-auto-v1';
let storageOK=true,initialSave=null,initialQueue=null,initialHidden=null;
try{initialSave=localStorage.getItem(SAVE);initialQueue=localStorage.getItem(QUEUE);initialHidden=localStorage.getItem(HIDDEN);}catch{storageOK=false;}
let state=restoreState(initialSave)||initialState();
const initialManual=initialQueue===null?SEED_MEDIA.map(x=>x.url):restoreQueue(initialQueue);
let view={tab:'studio',manualQueue:initialManual,hiddenAuto:restoreHidden(initialHidden),autoFeed:null,autoStatus:'loading',queue:initialManual.slice(),mediaIndex:0,immersive:false,mediaConsent:false};
let draft=null,modal='',opener=null,toastTimer=null,mediaTimer=null,activeFrame=null,player=null,mediaGeneration=0,priorScroll=0,swipeStart=null;
const app=document.querySelector('#app'),dialog=document.querySelector('#dialog');
function toast(text){if(view.immersive){setStatus(text);return;}const box=document.querySelector('#toast');box.textContent=text;box.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.classList.remove('visible'),3800);}
function save(){try{localStorage.setItem(SAVE,JSON.stringify(state));localStorage.setItem(QUEUE,JSON.stringify(view.manualQueue));localStorage.setItem(HIDDEN,JSON.stringify(view.hiddenAuto));}catch{if(storageOK)toast('保存できないため、この画面を閉じるまでのプレイになります。');storageOK=false;}}
function rebuildQueue(preferred){view.queue=mergeMediaQueues(view.manualQueue,view.autoFeed?.videos||[],view.hiddenAuto);const index=preferred?view.queue.indexOf(preferred):-1;view.mediaIndex=index>=0?index:Math.min(view.mediaIndex,Math.max(0,view.queue.length-1));}
async function loadAutoVideos(){if(typeof fetch!=='function'){view.autoStatus='unavailable';return;}const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);try{const response=await fetch('./data/youtube-videos.json',{cache:'no-cache',signal:controller.signal});if(!response.ok)throw new Error('metadata');const raw=await response.text();if(raw.length>250000)throw new Error('size');const feed=validateAutoFeed(JSON.parse(raw));if(!feed)throw new Error('format');const preferred=view.tab==='media'?view.queue[view.mediaIndex]:null;view.autoFeed=feed;view.autoStatus='ready';if(!preferred)view.mediaIndex=0;rebuildQueue(preferred);}catch{view.autoStatus='unavailable';}finally{clearTimeout(timeout);if(view.tab==='media'&&!dialog.open&&!player&&!activeFrame&&!document.querySelector('.player-loading'))render(true);}}
function closeMedia(){mediaGeneration++;clearTimeout(mediaTimer);if(player){try{player.destroy();}catch{}player=null;}if(activeFrame){activeFrame.remove();activeFrame=null;}}
function render(focus=false){closeMedia();if(view.immersive){document.querySelector('#toast').classList.remove('visible');clearTimeout(toastTimer);}document.body.classList.toggle('immersive-active',view.immersive);app.innerHTML=renderApp(state,view);if(focus)document.querySelector('#main-content')?.focus({preventScroll:view.immersive});if(view.immersive&&view.mediaConsent&&!dialog.open&&view.queue.length)void loadMedia();}
function closeDialog(){if(dialog.open)dialog.close();modal='';draft=null;if(opener?.isConnected)opener.focus();else document.querySelector('#main-content')?.focus();}
function showDialog(kind,content){if(view.tab==='media'){view.mediaConsent=false;render(true);}if(!dialog.open)opener=document.activeElement;modal=kind;dialog.innerHTML=content;if(!dialog.open)dialog.showModal();const focus=dialog.querySelector('[autofocus],button,input');focus?.focus();}
function draftRender(focusAction,focusId){dialog.innerHTML=renderComposer(state,draft);if(focusAction)dialog.querySelector(`[data-action="${focusAction}"][data-id="${focusId}"]`)?.focus();}
function showResult(){showDialog('result',renderResult(state));}
function showSummary(){showDialog('summary',renderSummary(state));}
function setStatus(message){const node=document.querySelector('#embed-status');if(node)node.textContent=message;}
async function youtubeAPI(){if(window.YT?.Player)return window.YT;return new Promise((resolve,reject)=>{const prior=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{prior?.();resolve(window.YT);};const existing=document.querySelector('script[data-youtube-api]');if(!existing){const script=document.createElement('script');script.dataset.youtubeApi='true';script.src='https://www.youtube.com/iframe_api';script.onerror=()=>{script.remove();reject(new Error('script'));};document.head.append(script);}setTimeout(()=>window.YT?.Player?resolve(window.YT):reject(new Error('timeout')),12000);});}
async function loadMedia(){
 const media=parseMediaUrl(view.queue[view.mediaIndex]);if(!media)return;if(view.immersive)view.mediaConsent=true;closeMedia();const generation=mediaGeneration;
 const mount=document.querySelector('#embed-mount');mount.innerHTML='<div class="player-loading">公式プレーヤーに接続中…</div>';setStatus('外部サービスに接続中。再生できない場合は下の元リンクをご利用ください。');document.querySelector('#unload-button')?.classList.remove('hidden');
 mediaTimer=setTimeout(()=>{if(generation===mediaGeneration)setStatus('読み込みに時間がかかっています。元のサービスで開くか、閉じてもう一度お試しください。');},15000);
 if(media.platform==='youtube'){
  try{const YT=await youtubeAPI();if(generation!==mediaGeneration)return;mount.innerHTML='<div id="youtube-player"></div>';player=new YT.Player('youtube-player',{host:'https://www.youtube-nocookie.com',width:'100%',height:'100%',videoId:media.id,playerVars:{autoplay:0,playsinline:1,origin:location.origin},events:{onReady:()=>{if(generation!==mediaGeneration)return;clearTimeout(mediaTimer);setStatus('再生はプレーヤーの ▶ から。実際の視聴はゲームの数字に影響しません。');const f=mount.querySelector('iframe');if(f){f.title='YouTube公式動画プレーヤー';f.referrerPolicy='strict-origin-when-cross-origin';}},onError:event=>{if(generation!==mediaGeneration)return;clearTimeout(mediaTimer);const reason=event.data===100?'削除済み・非公開の可能性があります。':[101,150].includes(event.data)?'この動画は埋め込み再生が許可されていません。':event.data===153?'この環境ではプレーヤーの識別情報を送れません。':'この動画をここでは再生できません。';setStatus(`${reason} 下のYouTubeリンクで確認してください。`);}}});
  }catch{if(generation!==mediaGeneration)return;clearTimeout(mediaTimer);mount.innerHTML='<div class="player-fallback"><span>↗</span><h3>ここでは読み込めませんでした</h3><p>接続やブラウザーの設定により、<br>埋め込みを表示できないことがあります。</p><button class="secondary" data-action="load-media">もう一度試す</button></div>';setStatus('下のYouTubeリンクから元の動画を開けます。');}
 }else{
  mount.innerHTML='';const iframe=document.createElement('iframe');iframe.title='X公式投稿プレーヤー';iframe.src=`./x-embed.html?id=${encodeURIComponent(media.id)}`;iframe.setAttribute('sandbox','allow-scripts allow-popups allow-popups-to-escape-sandbox');iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.allow='encrypted-media; fullscreen; picture-in-picture';iframe.className='x-frame';activeFrame=iframe;mount.append(iframe);setStatus('X公式投稿を読み込み中。表示されない場合は元のXリンクをご利用ください。');
 }
}
window.addEventListener('message',event=>{if(!activeFrame||event.source!==activeFrame.contentWindow||event.data?.source!=='creator-pocket-x')return;if(event.data.type==='ready'){clearTimeout(mediaTimer);setStatus('X公式投稿です。実際の視聴はゲームの数字に影響しません。');}else if(event.data.type==='error'){clearTimeout(mediaTimer);setStatus('X投稿を表示できません。削除・公開範囲・接続制限をご確認のうえ、元のXリンクで開いてください。');}else if(event.data.type==='height'&&Number.isFinite(event.data.height)){activeFrame.style.height=`${Math.min(1200,Math.max(320,event.data.height))}px`;}});
document.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el)return;event.preventDefault();const action=el.dataset.action;if(el.disabled)return;
 try{
 if(action==='tab'){view.immersive=false;view.mediaConsent=false;closeDialog();view.tab=el.dataset.tab;render(true);window.scrollTo({top:0});return;}
 if(action==='enter-immersive'){if(!view.queue.length)return;priorScroll=window.scrollY;view.immersive=true;view.mediaConsent=false;render(true);window.scrollTo({top:0});return;}
 if(action==='exit-immersive'){view.immersive=false;view.mediaConsent=false;swipeStart=null;render();window.scrollTo({top:priorScroll});document.querySelector('[data-action=enter-immersive]')?.focus({preventScroll:true});return;}
 if(action==='add-immersive'){view.mediaConsent=false;showDialog('add-media',`<div class="dialog-heading"><h2 id="dialog-title">動画をキューに追加</h2><button class="icon-button" data-action="close" aria-label="閉じる">${icon('close')}</button></div><form id="url-form"><label for="video-url">公開されているYouTube / X投稿のURL</label><div class="url-row"><input id="video-url" name="url" type="url" required maxlength="2048" autocomplete="off" placeholder="https://youtube.com/shorts/…"><button class="secondary" type="submit">追加</button></div><p class="field-hint">追加後も、有効にするまで外部接続しません。</p></form>`);return;}
 if(action==='compose'){if(state.phase!=='planning')return;draft={ideaId:getIdeas(state)[0].id,format:'short',edit:'captions'};showDialog('compose',renderComposer(state,draft));return;}
 if(action.startsWith('choose-')&&modal==='compose'){const key={'choose-idea':'ideaId','choose-format':'format','choose-edit':'edit'}[action];if(key){draft[key]=el.dataset.id;draftRender(action,el.dataset.id);}return;}
 if(action==='publish'){if(modal!=='compose'||state.phase!=='planning')return;state=publish(state,draft);save();render(true);showResult();return;}
 if(action==='rest'){showDialog('rest-confirm',`<div class="dialog-heading"><h2 id="dialog-title">今日は、ひと休み？</h2><button class="icon-button" data-action="close" aria-label="閉じる">${icon('close')}</button></div><div class="rest-confirm"><span>☁</span><p>元気が最大35回復して、一日が進みます。<br>フォロワーやコインは減りません。</p><button class="primary wide" data-action="confirm-rest">今日は休む</button><button class="text-button wide" data-action="close">やっぱり作ってみる</button></div>`);return;}
 if(action==='confirm-rest'){if(state.phase!=='planning')return;state=rest(state);save();render(true);showResult();return;}
 if(action==='continue'){if(state.phase!=='result')return;state=continueDay(state);save();closeDialog();render(true);document.querySelector('[data-action=compose]')?.focus();window.scrollTo({top:0});if(state.phase==='summary')showSummary();return;}
 if(action==='result'){showResult();return;}if(action==='summary'){showSummary();return;}
 if(action==='next-week'){state=startWeek(state);save();closeDialog();render(true);return;}
 if(action==='upgrade'){state=upgrade(state,el.dataset.gear);save();render(true);toast('部屋が、少し作りやすくなりました。');return;}
 if(action==='close'){closeDialog();return;}if(action==='privacy'){showDialog('privacy',renderPrivacy());return;}
 if(action==='reset'){showDialog('reset-confirm',`<div class="dialog-heading"><h2 id="dialog-title">ゲームをはじめから？</h2><button class="icon-button" data-action="close" aria-label="閉じる">${icon('close')}</button></div><p>このブラウザーのゲーム進行・作品・道具が初期状態に戻ります。動画キューは残ります。</p><button class="primary wide" data-action="confirm-reset">はじめから遊ぶ</button><button class="text-button wide" data-action="close">戻る</button>`);return;}
 if(action==='confirm-reset'){state=initialState();save();closeDialog();view.tab='studio';render(true);return;}
 if(action==='load-media'){await loadMedia();return;}if(action==='unload-media'){view.mediaConsent=false;render(true);return;}
 if(['prev-media','next-media','select-media','remove-media'].includes(action)){if(action==='remove-media'){const url=el.dataset.url,current=view.queue[view.mediaIndex],removed=removeQueueEntry(view.manualQueue,view.autoFeed?.videos||[],view.hiddenAuto,url);view.manualQueue=removed.manual;view.hiddenAuto=removed.hidden;rebuildQueue(url===current?undefined:current);save();}else{view.mediaIndex=action==='prev-media'?Math.max(0,view.mediaIndex-1):action==='next-media'?Math.min(view.queue.length-1,view.mediaIndex+1):Math.max(0,view.queue.indexOf(el.dataset.url));}render(true);return;}
 }catch(error){toast(error.message||'もう一度試してください。');}
});
document.addEventListener('submit',event=>{if(event.target.id!=='url-form')return;event.preventDefault();const input=event.target.elements.url,media=parseMediaUrl(input.value);if(!media){toast('公開されているYouTube・X投稿の https:// URLを入れてください。');input.focus();return;}if(view.queue.some(url=>{const m=parseMediaUrl(url);return m.id===media.id&&m.platform===media.platform;})){toast('その動画は、もうキューにあります。');return;}if(view.manualQueue.length>=30){toast('手動URLは30件まで。不要なリンクを外してください。');return;}view.manualQueue.push(media.url);rebuildQueue(media.url);save();if(modal==='add-media')closeDialog();render(true);toast('マイキューに追加しました。');});
dialog.addEventListener('cancel',event=>{event.preventDefault();closeDialog();});
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeDialog();}});
function moveFeed(direction){if(!view.immersive||dialog.open)return;const next=nextFeedIndex(view.mediaIndex,direction,view.queue.length);if(next===view.mediaIndex){toast(direction>0?'キューの最後です。URLから動画を追加できます。':'キューの最初です。');return;}view.mediaIndex=next;render(true);}
document.addEventListener('pointerdown',event=>{if(!view.immersive||dialog.open)return;if(event.isPrimary===false){swipeStart=null;return;}if(event.button!==undefined&&event.button!==0)return;const area=event.target.closest?.('[data-swipe-area]');if(!area||event.target.closest?.('button,a,input,textarea,select'))return;swipeStart={x:event.clientX,y:event.clientY,id:event.pointerId};try{area.setPointerCapture?.(event.pointerId);}catch{}});
document.addEventListener('pointerup',event=>{if(!swipeStart||event.pointerId!==swipeStart.id)return;const start=swipeStart;swipeStart=null;const direction=swipeDirection(start,{x:event.clientX,y:event.clientY});if(direction)moveFeed(direction);});
for(const type of ['pointercancel','lostpointercapture'])document.addEventListener(type,()=>{swipeStart=null;});
document.addEventListener('keydown',event=>{if(!view.immersive||dialog.open||event.target.closest?.('input,textarea,select,[contenteditable=true]'))return;if(event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();moveFeed(event.key==='ArrowUp'?1:-1);}else if(event.key==='Escape'){document.querySelector('[data-action=exit-immersive]')?.click();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){try{player?.pauseVideo();}catch{}if(activeFrame){closeMedia();if(view.tab==='media'){view.mediaConsent=false;render(true);}}}});
window.addEventListener('pagehide',()=>{closeMedia();save();});
render(true);void loadAutoVideos();if(!storageOK)setTimeout(()=>toast('保存は利用できません。この画面を閉じるまで遊べます。'),500);else if(initialSave&&!restoreState(initialSave))setTimeout(()=>toast('保存データを読み込めなかったため、新しく始めました。'),500);
