import{initialState,getIdeas,preview,publish,rest,continueDay,upgrade,startWeek,restoreState,defaultDraft,applyMonetization,resolveEvent}from'./game.js';
import{validateAutoFeed,mergeMediaQueues,restoreHidden,removeQueueEntry}from'./auto-media.js';
import{swipeDirection,nextFeedIndex}from'./feed.js';
import{GENRES,createRecommendationState,loadRecommendationState,saveRecommendationState,setInterests,setVideoLiked,isVideoLiked,rankRecommendations}from'./recommendations.js';
import{SEED_MEDIA,parseMediaUrl,restoreQueue,canEmbedMedia}from'./media.js';
import{renderApp,renderComposer,renderResult,renderSummary,renderPrivacy,renderPostDetail,renderEquipment,icon}from'./render.js';
const SAVE='creator-pocket-v1',QUEUE='creator-pocket-queue-v1',HIDDEN='creator-pocket-hidden-auto-v1';
let storageOK=true,initialSave=null,initialQueue=null,initialHidden=null;
try{initialSave=localStorage.getItem(SAVE);initialQueue=localStorage.getItem(QUEUE);initialHidden=localStorage.getItem(HIDDEN);}catch{storageOK=false;}
let state=restoreState(initialSave)||initialState({seed:globalThis.crypto?.getRandomValues?crypto.getRandomValues(new Uint32Array(1))[0]:1});
let recommendations=createRecommendationState();try{recommendations=loadRecommendationState(localStorage);}catch{}
const initialManual=initialQueue===null?SEED_MEDIA.map(x=>x.url):restoreQueue(initialQueue);
let view={tab:'studio',recommendations,draftInterests:null,interestsOpen:false,manualQueue:initialManual,hiddenAuto:restoreHidden(initialHidden),autoFeed:null,autoStatus:'loading',queue:initialManual.slice(),mediaIndex:0,immersive:false,mediaConsent:false};
let draft=null;try{const saved=JSON.parse(localStorage.getItem('creator-pocket-draft-v2'));if(saved?.seed===state.seed&&saved?.day===state.day&&saved.draft&&['idea','format','hook','body','edit','review'].includes(saved.draft.step))draft={...defaultDraft(state),...saved.draft};}catch{}
function saveDraft(){try{if(draft){localStorage.setItem(SAVE,JSON.stringify(state));localStorage.setItem('creator-pocket-draft-v2',JSON.stringify({seed:state.seed,day:state.day,draft}));}else localStorage.removeItem('creator-pocket-draft-v2');}catch{}}
let modal='',opener=null,toastTimer=null,mediaTimer=null,activeFrame=null,player=null,mediaGeneration=0,priorScroll=0,swipeStart=null,lastTap=null;
const app=document.querySelector('#app'),dialog=document.querySelector('#dialog');
function toast(text){if(view.immersive){setStatus(text);return;}const box=document.querySelector('#toast');box.textContent=text;box.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.classList.remove('visible'),3800);}
function save(){try{localStorage.setItem(SAVE,JSON.stringify(state));localStorage.setItem(QUEUE,JSON.stringify(view.manualQueue));localStorage.setItem(HIDDEN,JSON.stringify(view.hiddenAuto));}catch{if(storageOK)toast('保存できないため、この画面を閉じるまでのプレイになります。');storageOK=false;}}
function recommendationEntry(url){const entry=view.autoFeed?.videos?.find(x=>x.url===url)||SEED_MEDIA.find(x=>x.url===url);return entry?{...entry,url}:{url};}
function rebuildQueue(preferred){const previousQueue=view.queue.slice(),activeIndex=view.mediaIndex,merged=mergeMediaQueues(view.manualQueue,view.autoFeed?.videos||[],view.hiddenAuto);view.queue=rankRecommendations(merged.map(recommendationEntry),view.recommendations,preferred?{activeKey:preferred,activeIndex,previousQueue}:{}).map(x=>x.url);const index=preferred?view.queue.indexOf(preferred):-1;view.mediaIndex=index>=0?index:Math.min(view.mediaIndex,Math.max(0,view.queue.length-1));}
function saveRecommendations(){try{return saveRecommendationState(localStorage,view.recommendations);}catch{return false;}}
function likeCurrentVideo(value){const url=view.queue[view.mediaIndex];if(!url)return;const liked=value??!isVideoLiked(view.recommendations,url);view.recommendations=setVideoLiked(view.recommendations,recommendationEntry(url),liked);const saved=saveRecommendations();rebuildQueue(url);for(const button of document.querySelectorAll('[data-action=like-media]')){button.setAttribute('aria-pressed',String(liked));button.setAttribute('aria-label',`この端末の好みに${liked?'保存済み。解除する':'保存する'}`);button.classList.toggle('liked',liked);button.innerHTML=`${liked?'♥':'♡'}<span>好み</span>`;}for(const feedback of document.querySelectorAll('.local-like-feedback'))feedback.textContent=liked?(saved?'♥ この端末の好みに保存しました':'♥ この画面の好みに保存しました（端末保存できません）'):'♡ 好みから外しました';document.querySelector('.swipe-rail')?.classList.toggle('is-liked',liked);}

async function loadAutoVideos(){if(typeof fetch!=='function'){view.autoStatus='unavailable';return;}const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);try{const response=await fetch('./data/youtube-videos.json',{cache:'no-cache',signal:controller.signal});if(!response.ok)throw new Error('metadata');const raw=await response.text();if(raw.length>250000)throw new Error('size');const feed=validateAutoFeed(JSON.parse(raw));if(!feed)throw new Error('format');const preferred=view.tab==='media'?view.queue[view.mediaIndex]:null;view.autoFeed=feed;view.autoStatus='ready';if(!preferred)view.mediaIndex=0;rebuildQueue(preferred);}catch{view.autoStatus='unavailable';}finally{clearTimeout(timeout);if(view.tab==='media'&&!dialog.open&&!player&&!activeFrame&&!document.querySelector('.player-loading'))render(true);}}
function closeMedia(){mediaGeneration++;clearTimeout(mediaTimer);if(player){try{player.destroy();}catch{}player=null;}if(activeFrame){activeFrame.remove();activeFrame=null;}}
function render(focus=false){swipeStart=null;lastTap=null;closeMedia();if(view.immersive){document.querySelector('#toast').classList.remove('visible');clearTimeout(toastTimer);}document.body.classList.toggle('immersive-active',view.immersive);app.innerHTML=renderApp(state,view);if(focus)document.querySelector('#main-content')?.focus({preventScroll:view.immersive});if(view.immersive&&view.mediaConsent&&!dialog.open&&view.queue.length)void loadMedia();}
function closeDialog(){if(dialog.open)dialog.close();modal='';if(opener?.isConnected)opener.focus();else document.querySelector('#main-content')?.focus();}
function showDialog(kind,content){if(view.tab==='media'){view.mediaConsent=false;render(true);}if(!dialog.open)opener=document.activeElement;modal=kind;dialog.innerHTML=content;if(!dialog.open)dialog.showModal();const focus=dialog.querySelector('[autofocus],button,input');focus?.focus();}
function draftRender(){saveDraft();dialog.innerHTML=renderComposer(state,draft);dialog.querySelector('.composer-stage button:not(:disabled),[data-action=publish],button')?.focus();dialog.scrollTop=0;}
function showResult(){showDialog('result',renderResult(state));}
function showSummary(){showDialog('summary',renderSummary(state));}
function setStatus(message){const node=document.querySelector('#embed-status');if(node)node.textContent=message;}
async function loadMedia(){
 const media=parseMediaUrl(view.queue[view.mediaIndex]);if(!canEmbedMedia(media)){setStatus('YouTubeは外部の公式ページで再生します。');return;}if(view.immersive)view.mediaConsent=true;closeMedia();const generation=mediaGeneration;
 const mount=document.querySelector('#embed-mount');mount.innerHTML='<div class="player-loading">公式プレーヤーに接続中…</div>';setStatus('外部サービスに接続中。再生できない場合は下の元リンクをご利用ください。');document.querySelector('#unload-button')?.classList.remove('hidden');
 mediaTimer=setTimeout(()=>{if(generation===mediaGeneration)setStatus('読み込みに時間がかかっています。元のサービスで開くか、閉じてもう一度お試しください。');},15000);
  mount.innerHTML='';const iframe=document.createElement('iframe');iframe.title='X公式投稿プレーヤー';iframe.src=`./x-embed.html?id=${encodeURIComponent(media.id)}`;iframe.setAttribute('sandbox','allow-scripts allow-popups allow-popups-to-escape-sandbox');iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.allow='encrypted-media; fullscreen; picture-in-picture';iframe.className='x-frame';activeFrame=iframe;mount.append(iframe);setStatus('X公式投稿を読み込み中。表示されない場合は元のXリンクをご利用ください。');
}
window.addEventListener('message',event=>{if(!activeFrame||event.source!==activeFrame.contentWindow||event.data?.source!=='creator-pocket-x')return;if(event.data.type==='ready'){clearTimeout(mediaTimer);setStatus('X公式投稿です。実際の視聴はゲームの数字に影響しません。');}else if(event.data.type==='error'){clearTimeout(mediaTimer);setStatus('X投稿を表示できません。削除・公開範囲・接続制限をご確認のうえ、元のXリンクで開いてください。');}else if(event.data.type==='height'&&Number.isFinite(event.data.height)){activeFrame.style.height=`${Math.min(1200,Math.max(320,event.data.height))}px`;}});
document.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el)return;event.preventDefault();const action=el.dataset.action;if(el.disabled)return;
 try{
 if(action==='tab'){view.immersive=false;view.mediaConsent=false;closeDialog();view.tab=el.dataset.tab;render(true);window.scrollTo({top:0});return;}
 if(action==='enter-immersive'){if(!view.queue.length)return;priorScroll=window.scrollY;view.immersive=true;view.mediaConsent=false;render(true);window.scrollTo({top:0});return;}
 if(action==='exit-immersive'){view.immersive=false;view.mediaConsent=false;swipeStart=null;render();window.scrollTo({top:priorScroll});document.querySelector('[data-action=enter-immersive]')?.focus({preventScroll:true});return;}
 if(action==='add-immersive'){view.mediaConsent=false;showDialog('add-media',`<div class="dialog-heading"><h2 id="dialog-title">動画をキューに追加</h2><button class="icon-button" data-action="close" aria-label="閉じる">${icon('close')}</button></div><form id="url-form"><label for="video-url">公開されているYouTube / X投稿のURL</label><div class="url-row"><input id="video-url" name="url" type="url" required maxlength="2048" autocomplete="off" placeholder="https://youtube.com/shorts/…"><button class="secondary" type="submit">追加</button></div><p class="field-hint">追加後も、有効にするまで外部接続しません。</p></form>`);return;}
 if(action==='like-media'){likeCurrentVideo();return;}
 if(action==='edit-interests'){view.draftInterests=view.recommendations.genres.slice();view.interestsOpen=true;view.mediaConsent=false;render();document.querySelector('.interest-chip')?.focus();return;}
 if(action==='toggle-interest'){if(!GENRES.some(g=>g.id===el.dataset.genre))return;view.interestsOpen=true;const selected=view.draftInterests||view.recommendations.genres.slice();view.draftInterests=selected.includes(el.dataset.genre)?selected.filter(x=>x!==el.dataset.genre):[...selected,el.dataset.genre];render();document.querySelector(`[data-genre="${el.dataset.genre}"]`)?.focus();return;}
 if(action==='save-interests'||action==='skip-interests'){view.recommendations=setInterests(view.recommendations,action==='skip-interests'?[]:view.draftInterests||view.recommendations.genres);const saved=saveRecommendations();view.interestsOpen=false;view.draftInterests=null;view.mediaIndex=0;view.mediaConsent=false;rebuildQueue();render(true);if(!saved)toast('好みはこの画面で反映します。端末には保存できませんでした。');return;}
 if(action==='compose'){if(state.phase!=='planning')return;if(!draft||draft.ideaId&&!getIdeas(state).some(x=>x.id===draft.ideaId))draft=defaultDraft(state);showDialog('compose',renderComposer(state,draft));return;}
 if(action.startsWith('choose-')&&modal==='compose'){const key={'choose-idea':'ideaId','choose-format':'format','choose-hook':'hook','choose-body':'body','choose-edit':'edit'}[action],next={'choose-idea':'format','choose-format':'hook','choose-hook':'body','choose-body':'edit','choose-edit':'review'}[action];if(key){draft[key]=el.dataset.id;draft.step=next;draftRender();}return;}
 if(action==='draft-back'&&modal==='compose'){const order=['idea','format','hook','body','edit','review'];draft.step=order[Math.max(0,order.indexOf(draft.step)-1)];draftRender();return;}
 if(action==='cheap-draft'&&modal==='compose'){draft.format='note';draft.edit='natural';draftRender();return;}
 if(action==='toggle-sponsored'&&modal==='compose'){draft.sponsored=!draft.sponsored;draftRender();return;}
 if(action==='publish'){if(modal!=='compose'||state.phase!=='planning')return;state=publish(state,draft);draft=null;saveDraft();save();render(true);showResult();return;}
 if(action==='channel-section'){view.channelSection=el.dataset.id;render(true);document.querySelector(`[data-action=channel-section][data-id="${view.channelSection}"]`)?.focus();return;}
 if(action==='equipment'){showDialog('equipment',`<div class="dialog-heading"><h2 id="dialog-title">スタジオと設定</h2><button class="icon-button" data-action="close" aria-label="閉じる">${icon('close')}</button></div>${renderEquipment(state)}`);return;}
 if(action==='post-detail'){showDialog('post-detail',renderPostDetail(state,el.dataset.id));return;}
 if(action==='plan-from-post'){const p=state.posts.find(x=>x.id===el.dataset.id);if(state.phase!=='planning'||!p)return;state={...state,plannedIdea:p.ideaId||null};draft=defaultDraft(state);save();saveDraft();view.tab='studio';render();showDialog('compose',renderComposer(state,draft));return;}
 if(action==='apply-monetization'){state=applyMonetization(state);save();render(true);toast('申請できました。次のゲーム内日に承認されます。');return;}
 if(action==='event'){state=resolveEvent(state,el.dataset.id,el.dataset.choice);save();render(true);return;}
 if(action==='rest'){showDialog('rest-confirm',`<div class="dialog-heading"><h2 id="dialog-title">今日は、ひと休み？</h2><button class="icon-button" data-action="close" aria-label="閉じる">${icon('close')}</button></div><div class="rest-confirm"><span>☁</span><p>元気が最大35回復して、一日が進みます。<br>フォロワーやコインは減りません。</p><button class="primary wide" data-action="confirm-rest">今日は休む</button><button class="text-button wide" data-action="close">やっぱり作ってみる</button></div>`);return;}
 if(action==='confirm-rest'){if(state.phase!=='planning')return;state=rest(state);save();render(true);showResult();return;}
 if(action==='continue'){if(state.phase!=='result')return;state=continueDay(state);draft=null;saveDraft();save();closeDialog();render(true);document.querySelector('[data-action=compose]')?.focus();window.scrollTo({top:0});if(state.phase==='summary')showSummary();return;}
 if(action==='result'){showResult();return;}if(action==='summary'){showSummary();return;}
 if(action==='next-week'){state=startWeek(state);save();closeDialog();render(true);return;}
 if(action==='upgrade'){state=upgrade(state,el.dataset.gear);save();render(true);if(modal==='equipment'){dialog.innerHTML=`<div class="dialog-heading"><h2 id="dialog-title">スタジオと設定</h2><button class="icon-button" data-action="close" aria-label="閉じる">${icon('close')}</button></div>${renderEquipment(state)}`;dialog.querySelector('[data-action=close]')?.focus();}toast('部屋が、少し作りやすくなりました。');return;}
 if(action==='close'){closeDialog();return;}if(action==='privacy'){showDialog('privacy',renderPrivacy());return;}
 if(action==='reset'){showDialog('reset-confirm',`<div class="dialog-heading"><h2 id="dialog-title">ゲームをはじめから？</h2><button class="icon-button" data-action="close" aria-label="閉じる">${icon('close')}</button></div><p>このブラウザーのゲーム進行・作品・道具が初期状態に戻ります。動画キューは残ります。</p><button class="primary wide" data-action="confirm-reset">はじめから遊ぶ</button><button class="text-button wide" data-action="close">戻る</button>`);return;}
 if(action==='confirm-reset'){state=initialState({seed:globalThis.crypto?.getRandomValues?crypto.getRandomValues(new Uint32Array(1))[0]:1});draft=null;saveDraft();save();closeDialog();view.tab='studio';render(true);return;}
 if(action==='load-media'){await loadMedia();return;}if(action==='unload-media'){view.mediaConsent=false;render(true);return;}
 if(['prev-media','next-media','select-media','remove-media'].includes(action)){if(action==='remove-media'){const url=el.dataset.url,current=view.queue[view.mediaIndex],removed=removeQueueEntry(view.manualQueue,view.autoFeed?.videos||[],view.hiddenAuto,url);view.manualQueue=removed.manual;view.hiddenAuto=removed.hidden;rebuildQueue(url===current?undefined:current);save();}else{view.mediaIndex=action==='prev-media'?Math.max(0,view.mediaIndex-1):action==='next-media'?Math.min(view.queue.length-1,view.mediaIndex+1):Math.max(0,view.queue.indexOf(el.dataset.url));}render(true);return;}
 }catch(error){toast(error.message||'もう一度試してください。');}
});
document.addEventListener('submit',event=>{if(event.target.id!=='url-form')return;event.preventDefault();const input=event.target.elements.url,media=parseMediaUrl(input.value);if(!media){toast('公開されているYouTube・X投稿の https:// URLを入れてください。');input.focus();return;}if(view.queue.some(url=>{const m=parseMediaUrl(url);return m.id===media.id&&m.platform===media.platform;})){toast('その動画は、もうキューにあります。');return;}if(view.manualQueue.length>=30){toast('手動URLは30件まで。不要なリンクを外してください。');return;}view.manualQueue.push(media.url);rebuildQueue(media.url);save();if(modal==='add-media')closeDialog();render(true);toast('マイキューに追加しました。');});
dialog.addEventListener('cancel',event=>{event.preventDefault();closeDialog();});
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeDialog();}});
function moveFeed(direction){if(!view.immersive||dialog.open)return;const next=nextFeedIndex(view.mediaIndex,direction,view.queue.length);if(next===view.mediaIndex){toast(direction>0?'キューの最後です。URLから動画を追加できます。':'キューの最初です。');return;}view.mediaIndex=next;render(true);}
document.addEventListener('pointerdown',event=>{if(!view.immersive||dialog.open)return;if(event.isPrimary===false){swipeStart=null;lastTap=null;return;}if(event.button!==undefined&&event.button!==0)return;const area=event.target.closest?.('[data-swipe-area]');if(!area||event.target.closest?.('button,a,input,textarea,select')){swipeStart=null;lastTap=null;return;}swipeStart={x:event.clientX,y:event.clientY,id:event.pointerId,time:event.timeStamp,likeArea:area.matches('[data-like-area]')};try{area.setPointerCapture?.(event.pointerId);}catch{}});
document.addEventListener('pointermove',event=>{if(swipeStart&&event.pointerId===swipeStart.id&&(Math.abs(event.clientX-swipeStart.x)>12||Math.abs(event.clientY-swipeStart.y)>12))swipeStart.dragged=true;});
document.addEventListener('pointerup',event=>{if(!swipeStart||event.pointerId!==swipeStart.id)return;const start=swipeStart;swipeStart=null;const direction=swipeDirection(start,{x:event.clientX,y:event.clientY});if(direction){lastTap=null;moveFeed(direction);return;}const tap=start.likeArea&&!start.dragged&&Math.abs(event.clientX-start.x)<=12&&Math.abs(event.clientY-start.y)<=12&&event.timeStamp-start.time<=450;if(!tap){lastTap=null;return;}const url=view.queue[view.mediaIndex],now=event.timeStamp;if(lastTap&&lastTap.url===url&&now-lastTap.time<=350&&Math.hypot(event.clientX-lastTap.x,event.clientY-lastTap.y)<=28){lastTap=null;likeCurrentVideo(true);}else lastTap={url,time:now,x:event.clientX,y:event.clientY};});
document.addEventListener('pointercancel',()=>{swipeStart=null;lastTap=null;});
document.addEventListener('lostpointercapture',()=>{if(swipeStart){swipeStart=null;lastTap=null;}});
document.addEventListener('keydown',event=>{if(!view.immersive||dialog.open||event.target.closest?.('input,textarea,select,[contenteditable=true]'))return;if(event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();moveFeed(event.key==='ArrowUp'?1:-1);}else if(event.key==='Escape'){document.querySelector('[data-action=exit-immersive]')?.click();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){try{player?.pauseVideo();}catch{}if(activeFrame){closeMedia();if(view.tab==='media'){view.mediaConsent=false;render(true);}}}});
window.addEventListener('pagehide',()=>{closeMedia();save();});
rebuildQueue();render(true);void loadAutoVideos();if(!storageOK)setTimeout(()=>toast('保存は利用できません。この画面を閉じるまで遊べます。'),500);else if(initialSave&&!restoreState(initialSave))setTimeout(()=>toast('保存データを読み込めなかったため、新しく始めました。'),500);

dialog.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;const group=event.target.closest('[role=radiogroup]');if(!group)return;const choices=[...group.querySelectorAll('[role=radio]:not(:disabled)')],index=choices.indexOf(event.target);if(index<0)return;event.preventDefault();choices[(index+(['ArrowRight','ArrowDown'].includes(event.key)?1:choices.length-1))%choices.length]?.focus();});
