import{parseMediaUrl,restoreQueue}from'./media.js';
const ID=/^[A-Za-z0-9_-]{11}$/,CHANNEL=/^UC[A-Za-z0-9_-]{22}$/;
const clean=(value,max)=>typeof value==='string'?value.replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,max):'';
const date=value=>typeof value==='string'&&value.length<50&&Number.isFinite(Date.parse(value))?new Date(value).toISOString():null;
export function validateAutoFeed(raw){if(!raw||raw.version!==1||!Array.isArray(raw.channels)||!Array.isArray(raw.videos)||raw.channels.length>20||raw.videos.length>500)return null;const channels=raw.channels.filter(c=>c&&CHANNEL.test(c.id)&&clean(c.title,100)).map(c=>({id:c.id,title:clean(c.title,100),status:clean(c.status,30),url:`https://www.youtube.com/channel/${c.id}`}));const byId=new Map(channels.map(c=>[c.id,c]));const seen=new Set();const videos=raw.videos.map(v=>{if(!v||!ID.test(v.id)||!byId.has(v.channelId)||!date(v.publishedAt))return null;const parsed=parseMediaUrl(v.url);if(parsed?.platform!=='youtube'||parsed.id!==v.id)return null;const title=clean(v.title,160);if(!title||seen.has(v.id))return null;seen.add(v.id);return{id:v.id,channelId:v.channelId,channelTitle:byId.get(v.channelId).title,title,publishedAt:date(v.publishedAt),updatedAt:date(v.updatedAt)||date(v.publishedAt),url:parsed.url};}).filter(Boolean).sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt)).slice(0,30);return{version:1,updatedAt:date(raw.updatedAt),checkedAt:date(raw.checkedAt),channels,videos};}
export function restoreHidden(raw){try{const arr=typeof raw==='string'?JSON.parse(raw):raw;if(!Array.isArray(arr))return[];return [...new Set(arr.filter(x=>typeof x==='string'&&ID.test(x)))].slice(-100);}catch{return[];}}
export function mergeMediaQueues(manual,automatic,hidden=[]){const excluded=new Set(restoreHidden(hidden));const auto=automatic.slice(0,30).filter(v=>v&&ID.test(v.id)&&!excluded.has(v.id)).map(v=>v.url);const result=[],seen=new Set();for(const raw of [...auto,...restoreQueue(manual)]){const m=parseMediaUrl(raw);if(!m)continue;const key=`${m.platform}:${m.id}`;if(seen.has(key))continue;seen.add(key);result.push(m.url);}return result.slice(0,60);}
export function removeQueueEntry(manual,automatic,hidden,url){const m=parseMediaUrl(url);if(!m)return{manual:restoreQueue(manual),hidden:restoreHidden(hidden)};const match=u=>{const p=parseMediaUrl(u);return p?.platform===m.platform&&p.id===m.id;};const nextManual=restoreQueue(manual).filter(u=>!match(u));const nextHidden=restoreHidden(hidden);if(m.platform==='youtube'&&automatic.some(v=>v.id===m.id))nextHidden.push(m.id);return{manual:nextManual,hidden:restoreHidden(nextHidden)};}
export function feedIsOverdue(feed,now=Date.now()){const checked=Date.parse(feed?.checkedAt);return !Number.isFinite(checked)||now-checked>12*60*60*1000;}
